apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: ClusterIP                   # type of service
  selector:
    app: myapp
    type: front-end
  ports:
  - port: 80                       # is port in service. Its a manditory field.
    targetPort: 80                 # port in pod. If we won't provide the targetPort it asumes to be the same as service port