apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort                   # type of service
  selector:
    app: myapp
    type: front-end
  ports:
  - port: 80                       # is port in service. Its a manditory field.
    targetPort: 80                 # port in pod. If we won't provide the targetPort it asumes to be the same as service port
    nodePort: 30008                # port in node. If we don't provide the nodeport it wll take any free port form the valid range(30000-32767)
